# Generated by Django 3.1.2 on 2020-12-10 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('tip', models.FloatField(default=0.0)),
                ('tax', models.FloatField()),
                ('stripeid', models.TextField()),
                ('password', models.TextField()),
                ('currency', models.TextField()),
                ('taxed', models.FloatField(default=0.0)),
                ('lastTaxedReset', models.DateTimeField()),
                ('lastTipReset', models.DateTimeField()),
                ('menuurl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('chosen', models.BooleanField(default=False)),
                ('tax', models.FloatField()),
                ('tip', models.FloatField()),
                ('cost', models.FloatField()),
                ('items', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('phonenum', models.TextField()),
                ('tablenum', models.IntegerField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_menu_api.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('item', models.TextField()),
                ('req', models.BooleanField(default=False)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_menu_api.restaurant')),
            ],
        ),
    ]
